version: '3.9'

networks:
  lemoncode-challenge:

services:
  frontend:
    build: 
      context: ./frontend
    environment:
      - API_URI=http://topics-api:5000/api/topics
    ports:
      - 8080:3000
    depends_on:
      - backend
    networks:
      - lemoncode-challenge

  backend:
    build: 
      context: ./backend
    depends_on:
      - mongodb
    networks:
      - lemoncode-challenge
    container_name: topics-api

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - lemoncode-challenge
    volumes:
      - ./mongo-data:/data/db
    container_name: some-mongo

